language: r
addons:
  apt:
    packages:
      - r-cran-rjava
      - libudunits2-dev
      - libgit2-dev
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo $(which R) CMD javareconf

r_github_packages:
  - spatstat/spatstat.sparse

script:
  - travis_wait 45