#' @importFrom methods setClass setGeneric setMethod setRefClass
NULL

#' @title ENMevaluation class
#' @description An S4 class that contains the ENMevaluate results. Objects of this class are generated by \code{ENMevaluate()}.
#' @author Jamie M. Kass, \email{jamie.m.kass@@gmail.com}, Bob Muscarella, \email{bob.muscarella@@gmail.com}
#' @slot algorithm character of algorithm used
#' @slot tune.settings data.frame of settings that were tuned
#' @slot partition.method character of partition method used
#' @slot results data.frame of evaluation summary statistics
#' @slot results.grp data.frame of evaluation k-fold statistics
#' @slot models list of model objects
#' @slot predictions RasterStack of model predictions
#' @slot occ.pts data.frame of occurrence coordinates used for model training
#' @slot occ.grp vector of partition groups for occurrence points
#' @slot bg.pts data.frame of background coordinates used for model training
#' @slot bg.grp vector of partition groups for background points
#' @slot overlap list of matrices of pairwise niche overlap statistics
#' @export

# class slots match older ENMeval versions
ENMevaluation <- setClass("ENMevaluation",
                          slots = c(algorithm = 'character',
                                  tune.settings = 'data.frame',
                                  partition.method = 'character',
                                  results = 'data.frame',
                                  results.grp = 'data.frame',
                                  models = 'list',
                                  predictions = 'RasterStack',
                                  occ.pts = 'data.frame',
                                  occ.grp = 'numeric',
                                  bg.pts = 'data.frame',
                                  bg.grp = 'numeric',
                                  overlap = 'list'))

setGeneric("algorithm", function(x) standardGeneric("algorithm"))
#' @export
setMethod("algorithm", "ENMevaluation", function(x) x@algorithm)

setGeneric("tune.settings", function(x) standardGeneric("tune.settings"))
#' @export
setMethod("tune.settings", "ENMevaluation", function(x) x@tune.settings)

setGeneric("results", function(x) standardGeneric("results"))
#' @export
setMethod("results", "ENMevaluation", function(x) x@results)

setGeneric("results.grp", function(x) standardGeneric("results.grp"))
#' @export
setMethod("results.grp", "ENMevaluation", function(x) x@results.grp)

setGeneric("predictions", function(x) standardGeneric("predictions"))
#' @export
setMethod("predictions", "ENMevaluation", function(x) x@predictions)

setGeneric("models", function(x) standardGeneric("models"))
#' @export
setMethod("models", "ENMevaluation", function(x) x@models)

setGeneric("partition.method", function(x) standardGeneric("partition.method"))
#' @export
setMethod("partition.method", "ENMevaluation", function(x) x@partition.method)

setGeneric("occ.pts", function(x) standardGeneric("occ.pts"))
#' @export
setMethod("occ.pts", "ENMevaluation", function(x) x@occ.pts)

setGeneric("occ.grp", function(x) standardGeneric("occ.grp"))
#' @export
setMethod("occ.grp", "ENMevaluation", function(x) x@occ.grp)

setGeneric("bg.pts", function(x) standardGeneric("bg.pts"))
#' @export
setMethod("bg.pts", "ENMevaluation", function(x) x@bg.pts)

setGeneric("bg.grp", function(x) standardGeneric("bg.grp"))
#' @export
setMethod("bg.grp", "ENMevaluation", function(x) x@bg.grp)

setGeneric("overlap", function(x) standardGeneric("overlap"))
#' @export
setMethod("overlap", "ENMevaluation", function(x) x@overlap)

#' @export
setMethod("show",
		  signature = "ENMevaluation",
		  definition = function(object) {
		  	cat("An object of class: ", class(object), "\n",
		  	" occurrence/background points: ",
		  	nrow(object@occ.pts), '/', nrow(object@bg.pts), "\n",
		  	" partition method: ", object@partition.method, "\n",
		  	" algorithm: ", object@algorithm, "\n",
		  	" tune settings: ", paste(apply(object@tune.settings, 1, function(x) paste(x, collapse = "")), collapse = ", "), "\n", 
		  	"Refer to ?ENMevaluation for information on slots.\n", sep = "")
		  	invisible(NULL)
		  })

#' @export
ENMdetails <- setClass("ENMdetails",
                       slots = c(fun = 'function',
                                 msgs = 'function',
                                 args = 'function',
                                 auc = 'function',
                                 pred = 'function',
                                 nparams = 'function'))
#' @export
ENMdetails <- function(fun, msgs, args, auc, pred, nparams) {
  # stopifnot(is.function(fun))
  # stopifnot(is.function(msgs))
  # stopifnot(is.function(args))
  # stopifnot(is.function(auc))
  # stopifnot(is.function(pred))
  # stopifnot(is.function(nparams))
  new("ENMdetails", fun = fun, msgs = msgs, args = args,
      auc = auc, pred = pred, nparams = nparams)
}

setGeneric("enm.fun", function(x) standardGeneric("enm.fun"))
setGeneric("enm.fun<-", function(x, value) standardGeneric("enm.fun<-"))
#' @export
setMethod("enm.fun", "ENMdetails", function(x) x@fun)
#' @export
setMethod("enm.fun<-", "ENMdetails", function(x, value) {
  x@fun <- value
  validObject(x)
  x
})

setGeneric("enm.msgs", function(x) standardGeneric("enm.msgs"))
setGeneric("enm.msgs<-", function(x, value) standardGeneric("enm.msgs<-"))
#' @export
setMethod("enm.msgs", "ENMdetails", function(x) x@msgs)
#' @export
setMethod("enm.msgs<-", "ENMdetails", function(x, value) {
  x@msgs <- value
  validObject(x)
  x
})

setGeneric("enm.args", function(x) standardGeneric("enm.args"))
setGeneric("enm.args<-", function(x, value) standardGeneric("enm.args<-"))
#' @export
setMethod("enm.args", "ENMdetails", function(x) x@args)
#' @export
setMethod("enm.args<-", "ENMdetails", function(x, value) {
  x@args <- value
  validObject(x)
  x
})

setGeneric("enm.auc", function(x) standardGeneric("enm.auc"))
setGeneric("enm.auc<-", function(x, value) standardGeneric("enm.auc<-"))
#' @export
setMethod("enm.auc", "ENMdetails", function(x) x@auc)
#' @export
setMethod("enm.auc<-", "ENMdetails", function(x, value) {
  x@auc <- value
  validObject(x)
  x
})

setGeneric("enm.pred", function(x) standardGeneric("enm.pred"))
setGeneric("enm.pred<-", function(x, value) standardGeneric("enm.pred<-"))
#' @export
setMethod("enm.pred", "ENMdetails", function(x) x@pred)
#' @export
setMethod("enm.pred<-", "ENMdetails", function(x, value) {
  x@pred <- value
  validObject(x)
  x
})

setGeneric("enm.nparam", function(x) standardGeneric("enm.nparam"))
setGeneric("enm.nparam<-", function(x, value) standardGeneric("enm.nparam<-"))
#' @export
setMethod("enm.nparam", "ENMdetails", function(x) x@nparam)
#' @export
setMethod("enm.nparam<-", "ENMdetails", function(x, value) {
  x@nparam <- value
  validObject(x)
  x
})
