#' @importFrom methods setClass setGeneric setMethod setRefClass
NULL

#' @title ENMevaluation class
#' @description An S4 class that contains the ENMevaluate results. The slots in this object are filled in by \code{ENMevaluate()} internally.
#' @author Jamie M. Kass, \email{jamie.m.kass@@gmail.com}, Bob Muscarella, \email{bob.muscarella@@gmail.com}
#' @slot algorithm character of algorithm used
#' @slot tune.settings data.frame of settings that were tuned
#' @slot partition.method character of partition method used
#' @slot results data.frame of evaluation summary statistics
#' @slot results.grp data.frame of evaluation k-fold statistics
#' @slot models list of model objects
#' @slot predictions RasterStack of model predictions
#' @slot occs data.frame of occurrence coordinates and predictor variable values used for model training
#' @slot occ.grp vector of partition groups for occurrence points
#' @slot bg data.frame of background coordinates and predictor variable values used for model training
#' @slot bg.grp vector of partition groups for background points
#' @slot overlap list of matrices of pairwise niche overlap statistics
#' @export

# class slots match older ENMeval versions
ENMevaluation <- setClass("ENMevaluation",
                          slots = c(algorithm = 'character',
                                  tune.settings = 'data.frame',
                                  partition.method = 'character',
                                  results = 'data.frame',
                                  results.grp = 'data.frame',
                                  models = 'list',
                                  predictions = 'RasterStack',
                                  occs = 'data.frame',
                                  occ.grp = 'factor',
                                  bg = 'data.frame',
                                  bg.grp = 'factor',
                                  overlap = 'list'))

setGeneric("algorithm", function(x) standardGeneric("algorithm"))
#' @export
setMethod("algorithm", "ENMevaluation", function(x) x@algorithm)

setGeneric("tune.settings", function(x) standardGeneric("tune.settings"))
#' @export
setMethod("tune.settings", "ENMevaluation", function(x) x@tune.settings)

setGeneric("results", function(x) standardGeneric("results"))
#' @export
setMethod("results", "ENMevaluation", function(x) x@results)

setGeneric("results.grp", function(x) standardGeneric("results.grp"))
#' @export
setMethod("results.grp", "ENMevaluation", function(x) x@results.grp)

setGeneric("predictions", function(x) standardGeneric("predictions"))
#' @export
setMethod("predictions", "ENMevaluation", function(x) x@predictions)

setGeneric("models", function(x) standardGeneric("models"))
#' @export
setMethod("models", "ENMevaluation", function(x) x@models)

setGeneric("partition.method", function(x) standardGeneric("partition.method"))
#' @export
setMethod("partition.method", "ENMevaluation", function(x) x@partition.method)

setGeneric("occs", function(x) standardGeneric("occs"))
#' @export
setMethod("occs", "ENMevaluation", function(x) x@occs)

setGeneric("occ.grp", function(x) standardGeneric("occ.grp"))
#' @export
setMethod("occ.grp", "ENMevaluation", function(x) x@occ.grp)

setGeneric("bg", function(x) standardGeneric("bg"))
#' @export
setMethod("bg", "ENMevaluation", function(x) x@bg)

setGeneric("bg.grp", function(x) standardGeneric("bg.grp"))
#' @export
setMethod("bg.grp", "ENMevaluation", function(x) x@bg.grp)

setGeneric("overlap", function(x) standardGeneric("overlap"))
#' @export
setMethod("overlap", "ENMevaluation", function(x) x@overlap)

#' @export
setMethod("show",
		  signature = "ENMevaluation",
		  definition = function(object) {
		  	cat("An object of class: ", class(object), "\n")
		  	cat(" occurrence/background points: ", nrow(object@occs), '/', nrow(object@bg), "\n")
		  	cat(" partition method: ", object@partition.method, "\n")
		  	cat(" algorithm: ", object@algorithm, "\n")
		  	cat(" tune settings: \n")
		  	print(object@tune.settings[,-ncol(object@tune.settings)], row.names = FALSE)
		  	cat(" overlap ", !is.null(object@overlap), "\n")
		  	cat("Refer to ?ENMevaluation for information on slots.", sep = "")
		  	invisible(NULL)
		  })

#' @title ENMdetails class
#' @description An S4 class that details packages, functions, messages associated with a specific species distribution model (SDM) or ecological niche model (ENM). 
#' Objects of this class are generated by \code{ENMdetails()}. For examples, look in the package's R folder for scripts beginning with "enm" -- these are 
#' pre-made ENMdetails object specifications that work with ENMeval out of the box.
#' @author Jamie M. Kass, \email{jamie.m.kass@@gmail.com}
#' @slot name character of name of model
#' @slot fun function that runs the model
#' @slot pkgs vector of package names needed to run the model function
#' @slot msgs function that prints messages showing the package version number, etc., and those related to the input tuning parameters \code{tune.args}
#' @slot args function specifying the parameters needed to run the model function
#' @slot aic function specifying how AIC should be calculated (if at all)
#' @slot eval function specifying how to calculate evaluation statistics (currently a specific parameterization of \code{dismo::evaluate()})
#' @slot kstats function specifying any additional cross-validation statistics to calculate on testing groups
#' @slot pred function specifying how to calculate a model prediction for a Raster* or a data frame
#' @slot nparams function specifying how to measure the number of model coefficients
#' @export

#' @export
ENMdetails <- setClass("ENMdetails",
                       slots = c(name = 'character',
                                 fun = 'function',
                                 pkgs = 'character',
                                 msgs = 'function',
                                 args = 'function',
                                 aic = 'function',
                                 eval = 'function',
                                 kstats = 'function',
                                 pred = 'function',
                                 nparams = 'function'))
#' @export
ENMdetails <- function(name, fun, pkgs, msgs, args, aic, eval, kstats, pred, nparams) {
  new("ENMdetails", name = name, fun = fun, pkgs = pkgs, msgs = msgs, args = args,
      aic = aic, eval = eval, kstats = kstats, pred = pred, nparams = nparams)
}

setGeneric("enm.name", function(x) standardGeneric("enm.name"))
setGeneric("enm.name<-", function(x, value) standardGeneric("enm.name<-"))
#' @export
setMethod("enm.name", "ENMdetails", function(x) x@name)
#' @export
setMethod("enm.name<-", "ENMdetails", function(x, value) {
  x@name <- value
  validObject(x)
  x
})


setGeneric("enm.fun", function(x) standardGeneric("enm.fun"))
setGeneric("enm.fun<-", function(x, value) standardGeneric("enm.fun<-"))
#' @export
setMethod("enm.fun", "ENMdetails", function(x) x@fun)
#' @export
setMethod("enm.fun<-", "ENMdetails", function(x, value) {
  x@fun <- value
  validObject(x)
  x
})

setGeneric("enm.pkgs", function(x) standardGeneric("enm.pkgs"))
setGeneric("enm.pkgs<-", function(x, value) standardGeneric("enm.pkgs<-"))
#' @export
setMethod("enm.pkgs", "ENMdetails", function(x) x@pkgs)
#' @export
setMethod("enm.pkgs<-", "ENMdetails", function(x, value) {
  x@pkgs <- value
  validObject(x)
  x
})

setGeneric("enm.msgs", function(x) standardGeneric("enm.msgs"))
setGeneric("enm.msgs<-", function(x, value) standardGeneric("enm.msgs<-"))
#' @export
setMethod("enm.msgs", "ENMdetails", function(x) x@msgs)
#' @export
setMethod("enm.msgs<-", "ENMdetails", function(x, value) {
  x@msgs <- value
  validObject(x)
  x
})

setGeneric("enm.args", function(x) standardGeneric("enm.args"))
setGeneric("enm.args<-", function(x, value) standardGeneric("enm.args<-"))
#' @export
setMethod("enm.args", "ENMdetails", function(x) x@args)
#' @export
setMethod("enm.args<-", "ENMdetails", function(x, value) {
  x@args <- value
  validObject(x)
  x
})

setGeneric("enm.aic", function(x) standardGeneric("enm.aic"))
setGeneric("enm.aic<-", function(x, value) standardGeneric("enm.aic<-"))
#' @export
setMethod("enm.aic", "ENMdetails", function(x) x@aic)
#' @export
setMethod("enm.aic<-", "ENMdetails", function(x, value) {
  x@aic <- value
  validObject(x)
  x
})

setGeneric("enm.eval", function(x) standardGeneric("enm.eval"))
setGeneric("enm.eval<-", function(x, value) standardGeneric("enm.eval<-"))
#' @export
setMethod("enm.eval", "ENMdetails", function(x) x@eval)
#' @export
setMethod("enm.eval<-", "ENMdetails", function(x, value) {
  x@eval <- value
  validObject(x)
  x
})

setGeneric("enm.kstats", function(x) standardGeneric("enm.kstats"))
setGeneric("enm.kstats<-", function(x, value) standardGeneric("enm.kstats<-"))
#' @export
setMethod("enm.kstats", "ENMdetails", function(x) x@kstats)
#' @export
setMethod("enm.kstats<-", "ENMdetails", function(x, value) {
  x@kstats <- value
  validObject(x)
  x
})

setGeneric("enm.pred", function(x) standardGeneric("enm.pred"))
setGeneric("enm.pred<-", function(x, value) standardGeneric("enm.pred<-"))
#' @export
setMethod("enm.pred", "ENMdetails", function(x) x@pred)
#' @export
setMethod("enm.pred<-", "ENMdetails", function(x, value) {
  x@pred <- value
  validObject(x)
  x
})

setGeneric("enm.nparam", function(x) standardGeneric("enm.nparam"))
setGeneric("enm.nparam<-", function(x, value) standardGeneric("enm.nparam<-"))
#' @export
setMethod("enm.nparam", "ENMdetails", function(x) x@nparam)
#' @export
setMethod("enm.nparam<-", "ENMdetails", function(x, value) {
  x@nparam <- value
  validObject(x)
  x
})

#' @export
setMethod("show",
          signature = "ENMdetails",
          definition = function(object) {
            cat("An object of class: ", class(object), "\n")
            cat(" Name: ", object@name, "\n")
            cat(" Packages: ", paste(object@pkgs, sep = ", "), "\n")
            cat("Refer to ?ENMdetails for information on slots, and to the vignette for how to construct a custom object.", sep = "")
            invisible(NULL)
          })
